### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by dazraf** [damiendallimore/SplunkJavaLogging#2]
Hi Damien,

Thank you for your library!

Do you think you could publish the latest and greatest release version to maven central? 
This would be good as it would avoid everyone needing to do the build and deploy to a local repository. 

Many thanks
Fuzz.

**Comment by damiendallimore** [comment]
See if this works

    <dependency>
      <groupId>splunkjavalogging</groupId>
      <artifactId>splunklogging</artifactId>
      <version>1.2</version>
    </dependency>
